custom_data_prep =  function(input_path, output_path){

  library(dplyr)
  library(reshape2)
  
  raw_data <- readRDS(file.path(input_path,"CCP_DASHBOARD_RAW.rda"))

  dic_data <- readRDS(file.path(input_path,"CCP_DASHBOARD_DIC.rda"))

  dic_data <- unique(dic_data)
  
  dic_data$value <- 'Y'

  names(dic_data)[2:3] <- c("PRODUCT_PART_NUM", "COMPONENT_TYPE")

  dic_data <- dcast(dic_data, PRODUCT_PART_NUM + COMPONENT_TYPE ~ PRODUCT_NAME, value.var = 'value')
  
  col_sel <- c("GROUP_FISCAL_YEAR_WEEK","GROUP_DATETIME","RECORD_FISCAL_YEAR_WEEK","RECORD_DATETIME","COMPONENT_TYPE","GROUP_NUM","PARTICLE_NAME","PARTICLE_VAL",
				 "PART_REV","PRODUCT_PART_NUM","SUPPLIER_NAME","SUB_SUPPLIER_NAME","SBR_NUM","SHIP_DATE")

  PARTICLE_select <- c("APA_CL_1_TOTAL_APA","APA_CL_3_1_SST_FEBASE_FEO","APA_CL_3_TOTAL_SEMI_APA","APA_CLASS_1_TOTAL_HPA","APA_CLASS_2_TOTAL_MAGNETIC","APA_CLASS_3_1_SST_FEBASED_FEO","APA_CLASS_3_2_SN_BASED","APA_CLASS_3_3_PZT","APA_CLASS_3_TOTAL_SEMI_HPA","APA_CLASS_4_TOTAL_SOFT_METAL","APA_CLASS_5_1_MGSIO","APA_CLASS_5_TOTAL_ENV","APA_CLASS_6_TOTAL_OTHER","APA_TOTAL_TI_BASED","BF_FTIR_SILICONE_CARBON_AS","BF_FTIR_SILICONE_CARBON_NO_AS","BF_FTIR_SILICONE_LINER_AS","BF_FTIR_SILICONE_LINER_BACK_AS","BF_IONIC_ANIONS_NITRITE","BF_IONIC_ANIONS_TOTAL_ANION","CHLORIDE","DHS_ALIPHATIC_HC","DHS_AROMATIC_HC","DHS_C1_0_ORGANOTIN","DHS_C10_0_NITRILES","DHS_C11_0_PHENOL_N_DERIV","DHS_C11_0_PHENOL_N_DERIVATIVE","DHS_C11_1_BHT","DHS_C11_2_IONOL_2","DHS_C12_0_ACRYLATE","DHS_C13_0_CYANOACRYLATE","DHS_C14_0_BIPHENYL_N_DERIV","DHS_C15_0_ACETOPHENONE_N_DERIV","DHS_C15_1__CHAP","DHS_C15_1_CHAP","DHS_C15_2_DM_ACETOPHENONE","DHS_C16_0_SILOXANE","DHS_C17_0_SILANES","DHS_C18_0_NAPHTHALENE_N_DERIV","DHS_C19_0_ALCOHOL","DHS_C19_1_BENZENEMETHANOL","DHS_C19_2_BUTANOL","DHS_C19_3_2ETHYL_HEXANOL","DHS_C2_0_ORGANOPHOSPHORUS","DHS_C20_0_AROMATIC_ESTER","DHS_C20_1_PHTHALATES","DHS_C21_0_ALIPHATIC_ESTER","DHS_C21_1_ETHYL_ACETATE","DHS_C22_0_KETONE","DHS_C22_1_BENZOQUINONE","DHS_C22_2_PENTANEDIONE","DHS_C23_0_ALDEHYDE","DHS_C23_1_BENZALDEHYDE","DHS_C24_0_ETHER","DHS_C24_1_DIOXANE","DHS_C24_2_DIOXOLANE","DHS_C25_0_AROMATIC_HC","DHS_C26_0_STYRENE_AND_AMS","DHS_C27_0_ALIPHATIC_HC","DHS_C28_0_HALOGEN_HC","DHS_C29_0_EPOXIDES","DHS_C3_0_ORGANOSULFUR","DHS_C30_0_CATIONIC_INITIATOR","DHS_C31_0_OTHERS","DHS_C32_0_UNKNOWNS","DHS_C33_0_UNRESOLVED_BANDS","DHS_C34_0_TOTAL_LOW_MW","DHS_C35_0_TOTAL_HIGH_MW","DHS_C4_0_ELEMENT_GAS_SULFUR","DHS_C4_0_ELEMENT_GASEOUS_S","DHS_C5_0_ORG_ACID_N_ANHYDRIDES","DHS_C5_1_ACRYLIC_ACID","DHS_C5_2_ETHYLHEXANOIC_ACID","DHS_C5_3_METHACRYLIC_ACID","DHS_C6_0_AROMATIC_ACID","DHS_C6_1_BENZOIC_ACID","DHS_C6_2_DIMETHYL_BENZOIC_ACID","DHS_C7_0_PEROXIDE","DHS_C8_0_AMIDE","DHS_C8_1_ACRYLAMIDE","DHS_C8_2_CAPROLACTAM","DHS_C9_0_AMINE","DHS_C9_1_TRIBUTYLAMINE","DHS_C9_2_DIPHENYLAMINE","DHS_NOT_LISTED_ABOVE_OTHERS","DHS_SILOXANE","DHS_STYRENE","DHS_TOTAL","DHS_TOTAL_OUTGASSING","DHS_UNKNOWNS","DHS_UNRESOLVED_BANDS","ECM_APA_CL_1_TOTAL_APA","ECM_APA_CL_3_1_SST_FEBASE_FEO","ECM_APA_CL_3_TOTAL_SEMI_APA","ECM_FTIR_SILICONE","ECM_FTIR_SILICONE_DESICCANT","ECM_IONIC_ANIONS_TOTAL_ANION","ECM_LPC_03","ENV_PARTICLE_TOTAL","EXTRACTABLE_BASE_RHC","EXTRACTABLE_BASE_TOC","EXTRACTABLE_HUB_RHC","EXTRACTABLE_HUB_TOC","EXTRACTABLE_N_ALKANE","EXTRACTABLE_RHC","FNCV_EXTRACTABLE_TOC","FTIR_AMIDE","FTIR_DOP","FTIR_HC","FTIR_HYDROCARBONS","FTIR_SILICON","FTIR_SILICONE","GCMS_ADDITIVE_A","GCMS_ADDITIVE_TINUVIN","GCMS_ADDITIVE_TOTAL_B","GCMS_EXTRACTABLE_BASE_TOC","GCMS_HYDROCARBON_TOC","GCMS_REPEATED_HYDROCARBON","GHOST","GHOST_TESTING_READING","GLOVE_LPC","GLOVE_MGSIO","IONIC_AMMONIUM","IONIC_ANIONS_FLUORIDE","IONIC_ANIONS_PHOSPHATE","IONIC_ANIONS_SULPHATE","IONIC_ANIONS_TOTAL_ANION","IONIC_BROMIDE","IONIC_CATIONS_AMMONIUM","IONIC_CHLORIDE","IONIC_FLUORIDE","IONIC_NITRATE","IONIC_NITRITE","IONIC_PHOSPHATE","IONIC_SULPHATE","LPC","LPC_03","LPC_06","LPC_PART1","LPC_PART2","LPC_PART3","MGSIO_CL5_1","N_ALKANE_TESTING_READ","N_ALKANE_TESTING_READING","NITRATE","NVR","NVR_DI_WATER","NVR_SOLVENT","PEAK_RATIO_DAILY_MIN","RF_EXTRACTABLES_GCMS_IRGAFOS","RF_FTIR_SILICONE","RF_HV_APEC_0_5_UM","RF_IONIC_ANIONS_TOTAL_ANION","RHC_TESTING_READING","RINSE_IONIC_AMMONIUM","RINSE_IONIC_BROMIDE","RINSE_IONIC_CHLORIDE","RINSE_IONIC_FLUORIDE","RINSE_IONIC_NITRATE","RINSE_IONIC_NITRITE","RINSE_IONIC_PHOSPHATE","RINSE_IONIC_SODIUM","RINSE_IONIC_SULPHATE","RINSE_NVR","SUPLPHATE","SUPPLY_BACTERIA","SUPPLY_IONIC_AMMONIUM","SUPPLY_IONIC_BROMIDE","SUPPLY_IONIC_CHLORIDE","SUPPLY_IONIC_FLUORIDE","SUPPLY_IONIC_NITRATE","SUPPLY_IONIC_NITRITE","SUPPLY_IONIC_PHOSPHATE","SUPPLY_IONIC_SODIUM","SUPPLY_IONIC_SULPHATE","SUPPLY_LPC","SUPPLY_PH","SUPPLY_RESISTIVITY","SUPPLY_SILICA","SUPPLY_TOC","SWAGEBALL_LPC","TOTAL_ANION","TOTAL_IONIC")

  raw_data <- raw_data[raw_data$PARTICLE_NAME %in% PARTICLE_select, col_sel]

  raw_data <- raw_data[grepl("2021",raw_data$GROUP_FISCAL_YEAR_WEEK),]

  raw_data <- left_join(raw_data, dic_data)

  raw_data <- unique(raw_data)

  write.csv(raw_data, file = file.path(output_path,"CCP_RAW_DATA.csv"), row.names = T, na = " ")

}